# Default values for sql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: akqahub.azurecr.io/sitecore-xm1-sqldev
  tag: 9.2.0-windowsservercore-1903
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 1433

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

  tls: []

persistence:
  dataSize:  5Gi

livenessprobe:
  initialDelaySeconds: 10
  periodSeconds: 20

readinessprobe:
  initialDelaySeconds: 10
  periodSeconds: 10

resources:  
  requests:
    memory: 4Gi

nodeSelector:
  beta.kubernetes.io/os: windows

tolerations: []

affinity: {}
