apiVersion: v1
kind: Service
metadata:
  name: {{ include "sql.name" . }}
  labels:
{{ include "sql.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    app.kubernetes.io/name: {{ include "sql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
